// Captains book their personal launch cue; everyone else books one shared JOIN cue. Radar dots move on the linear press→land clock.
const { chromium } = require("playwright");
const { basename } = require('node:path');
const { assertQaRoomName, makeQaRoom, qaRoomUrl, installQaWebSocketGuard, localQaBaseURL } = require('./support/qa-coordination.cjs');
(async () => {
  const HOST = localQaBaseURL(process.argv[2] || "http://127.0.0.1:8791");
  const RM = makeQaRoom({ title: basename(__filename, '.cjs') }), base = qaRoomUrl(HOST, RM, { notour: 1 });
  const b = await chromium.launch({ headless: true, channel: "chrome", args: ["--autoplay-policy=no-user-gesture-required"] });
  let pass = 0, fail = 0; const ok = (c, l) => { (c ? pass++ : fail++); console.log((c ? "✓" : "✗ FAIL") + " " + l); };
  const errs = [];
  const mk = async (fid, m, roomName = RM, roomBase = base) => { const context = await b.newContext({ viewport: { width: 390, height: 1200 }, locale: "en-US" }); await installQaWebSocketGuard(context, roomName, { expectedOrigin: HOST }); const p = await context.newPage(); p.on("pageerror", e => errs.push(fid + ":" + e.message)); await p.goto(roomBase); await p.waitForLoadState("networkidle"); await p.locator("#soundGate").click({ force: true }).catch(() => {}); await p.waitForTimeout(150); await p.locator("#pid").fill(fid); await p.waitForTimeout(1700); await p.locator("#marchRange").fill(String(m)); await p.locator("#saveBtn").click(); await p.waitForTimeout(500); return p; };
  const p1 = await mk("900000001", "60"), p2 = await mk("900000002", "70"), p3 = await mk("900000003", "80");
  const cmdContext = await b.newContext({ viewport: { width: 390, height: 1200 }, locale: "en-US" });
  await installQaWebSocketGuard(cmdContext, RM, { expectedOrigin: HOST });
  const cmd = await cmdContext.newPage();
  cmd.on("pageerror", e => errs.push("cmd:" + e.message));
  await cmd.goto(base); await cmd.waitForLoadState("networkidle");
  await cmd.locator("#soundGate").click({ force: true }).catch(() => {}); await cmd.waitForTimeout(150);
  await cmd.locator("#cmdUnlock").click(); await cmd.locator("#pwInput").fill("666"); await cmd.locator("#pwGo").click(); await cmd.waitForTimeout(2200);
  await cmd.locator('#roster .rp:has-text("900000001")').first().click(); await cmd.waitForTimeout(200);
  await cmd.locator('#roster .rp:has-text("900000002")').first().click(); await cmd.waitForTimeout(300);
  await cmd.locator('#lead button[data-v="10"]').click(); await cmd.waitForTimeout(150);
  await cmd.locator("#fireDouble").click(); await cmd.waitForTimeout(250); await cmd.locator("#fireDouble").click(); await p1.waitForTimeout(1500);
  const cueKeys = async page => page.evaluate(() => Object.keys(window.__cues || {}));
  const captainKeys = await cueKeys(p1), joinerKeys = await cueKeys(p3), commanderKeys = await cueKeys(cmd);
  ok(captainKeys.some(key => key.includes('-me:')), "selected captain books personal cues");
  ok(joinerKeys.some(key => key.includes('-join:')), "ordinary member books one JOIN countdown");
  ok(!commanderKeys.some(key => /-(?:me|join):/.test(key)), "unselected commander books no rally cues");
  ok(/Whales|🐋/i.test(await p3.locator("#pheroTitle").textContent() || ""), "joiner sees the matching whale countdown");
  await p3.locator("#cmdUnlock").click(); await p3.locator("#pwInput").fill("666"); await p3.locator("#pwGo").click(); await p3.waitForTimeout(1200);
  const promotedCommanderKeys = await cueKeys(p3);
  ok(!promotedCommanderKeys.some(key => /-(?:me|join):/.test(key)), "unlocking commander removes an already-booked JOIN countdown");
  // radar motion during GATHER: dot must creep toward the castle on the linear clock (used to be frozen for 5 min)
  const dist = async () => p3.evaluate(() => { const tr = [...document.querySelectorAll("#radar g")].map(g => g.getAttribute("transform")).filter(t => t && t.includes("translate")); const m = /translate\(([\d.]+),([\d.]+)\)/.exec(tr[0]); const dx = +m[1] - 180, dy = +m[2] - 66; return Math.hypot(dx, dy); });
  await p3.waitForTimeout(11000);   // past the press moment (lead 10s) — gather is running now
  const d0 = await dist(); await p3.waitForTimeout(8000); const d1 = await dist();
  ok(d1 < d0 - 0.2, "radar dot moves inward DURING the gather phase (" + d0.toFixed(1) + " → " + d1.toFixed(1) + ")");
  const selectedRoom = makeQaRoom({ title: `${basename(__filename, '.cjs')}-selected-commander` });
  const selectedBase = qaRoomUrl(HOST, selectedRoom, { notour: 1 });
  const selectedCmd = await mk("900000011", "60", selectedRoom, selectedBase);
  const selectedPeer = await mk("900000012", "70", selectedRoom, selectedBase);
  await selectedCmd.locator("#cmdUnlock").click(); await selectedCmd.locator("#pwInput").fill("666"); await selectedCmd.locator("#pwGo").click(); await selectedCmd.waitForTimeout(2200);
  await selectedCmd.locator('#roster .rp:has-text("900000011")').first().click(); await selectedCmd.waitForTimeout(200);
  await selectedCmd.locator('#roster .rp:has-text("900000012")').first().click(); await selectedCmd.waitForTimeout(300);
  await selectedCmd.locator('#lead button[data-v="10"]').click();
  await selectedCmd.locator("#fireDouble").click(); await selectedCmd.waitForTimeout(250); await selectedCmd.locator("#fireDouble").click(); await selectedCmd.waitForTimeout(1500);
  const selectedCommanderKeys = await cueKeys(selectedCmd);
  ok(selectedCommanderKeys.some(key => key.includes('-me:')), "selected commander books personal cues");
  ok(!selectedCommanderKeys.some(key => key.includes('-join:')), "selected commander never books JOIN cues");
  assertQaRoomName(RM); assertQaRoomName(selectedRoom);
  ok(errs.length === 0, "no page errors" + (errs.length ? " → " + errs.join(" | ") : ""));
  await Promise.race([b.close(), new Promise(resolve => setTimeout(resolve, 3000))]);
  console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
})().catch(e => { console.error("ERR", e.message); process.exit(2); });
