const { chromium } = require("playwright");
(async () => {
  const RM = "bg" + Date.now(), base = "https://kingshoter.com/kvk.html?k=test&room=" + RM;
  const b = await chromium.launch({ headless: true, channel: "chrome", args: ["--autoplay-policy=no-user-gesture-required"] });
  const dis = async p => { try { if (await p.locator("#obGo").isVisible()) await p.locator("#obGo").click(); } catch (e) {} };
  const mk = async (fid, secs) => { const p = await (await b.newContext({ viewport: { width: 390, height: 1000 }, locale: "en-US" })).newPage(); await p.goto(base); await p.waitForLoadState("networkidle"); await dis(p); await p.locator("#pid").fill(fid); await p.waitForTimeout(1700); await p.locator("#marchRange").fill(String(secs)); await p.locator("#saveBtn").click(); await p.waitForTimeout(800); return p; };
  const cmd = await (await b.newContext({ viewport: { width: 390, height: 1000 }, locale: "en-US" })).newPage();
  await cmd.goto(base); await cmd.waitForLoadState("networkidle"); await dis(cmd);
  await cmd.locator("#cmdFold > summary").click();
  await cmd.locator("#cmdUnlock").click(); await cmd.locator("#pwInput").fill("pw"); await cmd.locator("#pwGo").click(); await cmd.waitForTimeout(1000);
  const p1 = await mk("207573838", "95"), p2 = await mk("999999999", "70"); await cmd.waitForTimeout(900);
  console.log("roster rp count:", await cmd.locator("#roster .rp").count());
  await cmd.locator('#lead button[data-v="15"]').click();
  await cmd.locator("#roster .rp").nth(1).click(); await cmd.locator("#roster .rp").nth(0).click();
  console.log("selected rp:", await cmd.locator("#roster .rp.sel").count());
  await cmd.locator("#fireDouble").click(); await p1.waitForTimeout(1500);
  console.log("p1 bTitle:", JSON.stringify((await p1.locator("#bTitle").textContent() || "").trim()));
  console.log("p1 bCd:", JSON.stringify((await p1.locator("#bCd").textContent() || "").trim()));
  const st = await p1.evaluate(() => ({ hasRoom: !!window.room, acState: (window.__acProbe || "n/a") }));
  console.log("p1 state:", JSON.stringify(st));
  await b.close();
})().catch(e => { console.error("ERR", e.message); process.exit(2); });
